# Niki Doc AI Configuration (Test)

[project]
ignore = ["temp_test_dir"]

[context]
"custom_src" = "My Custom Source"

[[rules.python]]
id = "!RULE:NO_PRINT_TEST"
pattern = "print\\("
message = "Print is forbidden in test."
